### ISSUE TITLE
All 1x1 drawers have missing textures.

### ISSUE THREAD

**Issue by MagmaSlime123** [Mrthomas20121-Mods/Functional-TFC#1]
Title.

TFC 2.1.8 beta, functionalstorage 1.0.6, and Functional TFC 0.0.2.

![2022-09-24_22 15 41](https://user-images.githubusercontent.com/51277766/192128240-eefd4bd1-5494-4ddd-a650-3c459936b9fd.png)

**Comment by Mrthomas20121** [comment]
Fixed in dev
